network:
  version: 2
  ethernets:
    enp1s0:
      match:
        macaddress: "52:54:00:ff:f3:93"
      dhcp4: false
      dhcp6: true
      addresses:
        - 10.0.2.17/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 192.168.1.12
          via: 192.168.1.1
        - to: default
          via: 10.0.2.2
      set-name: "enp1s0"
